---
adjectives:
  - arrogant
  - beautiful
  - best
  - biggest
  - circular
  - competent
  - confusing
  - courageous
  - cumbersome
  - dainty
  - dark
  - devoted
  - efficient
  - expensive
  - fickle
  - generous
  - graceful
  - grumpy
  - happiest
  - helpful
  - hopeful
  - hot
  - hungry
  - mild
  - modern
  - muscular
  - new
  - new
  - oldest
  - oval
  - petite
  - prettiest
  - proud
  - rich
  - rocky
  - round
  - round
  - royal
  - rude
  - safe
  - scary
  - sleepy
  - small
  - smart
  - smelly
  - stable
  - strange
  - strange
  - tardy
  - thin
  - weary
  - wicked
  - witty
  - wooden
  - youthful
  - zany